# Generated by Django 5.0.6 on 2024-06-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("title", models.CharField(max_length=25)),
                ("date", models.DateField()),
                ("is_anniversary", models.BooleanField()),
                ("remark", models.TextField()),
            ],
        ),
    ]
